In [30]:
import laspy
import numpy as np
import pandas as pd


def load_file(
    filename,
    plot_centre=None,
    plot_radius=0,
    plot_radius_buffer=0,
    silent=False,
    headers_of_interest=None,
    return_num_points=False,
):
    if headers_of_interest is None:
        headers_of_interest = []
    if not silent:
        print("Loading file...", filename)
    file_extension = filename[-4:]
    coord_headers = ["x", "y", "z"]
    output_headers = []

    if file_extension == ".las" or file_extension == ".laz":
        try:
            inFile = laspy.read(filename)
        except FileNotFoundError:
            print(filename, "not found.")
            if return_num_points:
                return np.zeros((0, 3)), None, 0
            else:
                return np.zeros((0, 3)), None

        header_names = list(inFile.point_format.dimension_names)
        pointcloud = np.vstack((inFile.x, inFile.y, inFile.z))
        if len(headers_of_interest) != 0:
            headers_of_interest = headers_of_interest[3:]
            for header in headers_of_interest:
                if header in header_names:
                    pointcloud = np.vstack((pointcloud, getattr(inFile, header)))
                    output_headers.append(header)
        pointcloud = pointcloud.transpose()

    elif file_extension == ".csv":
        pointcloud = np.array(pd.read_csv(filename, header=None, index_col=None, delim_whitespace=True))

    original_num_points = pointcloud.shape[0]

    if plot_centre is None:
        mins = np.min(pointcloud[:, :2], axis=0)
        maxes = np.max(pointcloud[:, :2], axis=0)
        plot_centre = (maxes + mins) / 2
        print("Mins: " + str(mins))
        print("Maxes: " + str(maxes))
        print(plot_centre)

    if plot_radius > 0:
        distances = np.linalg.norm(pointcloud[:, :2] - plot_centre, axis=1)
        keep_points = distances < plot_radius + plot_radius_buffer
        pointcloud = pointcloud[keep_points]

    if return_num_points:
        return pointcloud, coord_headers + output_headers, original_num_points
    else:
        return pointcloud, coord_headers + output_headers



In [35]:
file_path_processed = "D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Small_Testing\Riverton_park_01_small - Copy.las"
file_path ="D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Small_Testing\small_export.las"
# file_path_modified = "D:\photogammetry\Projects\Flaming Tree Solutions\Exports\cleaned_cyl_vis.las"

# file_path = "D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Riverton_park_02_large.las"
# file_path_processed = "D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Riverton_park_02_large_FSCT_output\segmented_cleaned.las"

pc,cords,num= load_file(file_path,return_num_points=True)
pc_p,cords_p,num_p = load_file(file_path_processed,return_num_points=True)
# pc_m,cords_m,num_m = load_file(file_path_modified,return_num_points=True)


Loading file... D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Small_Testing\small_export.las
Mins: [ 713424.312 4766904.865]
Maxes: [ 713542.452 4767007.433]
[ 713483.382 4766956.149]
Loading file... D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Small_Testing\Riverton_park_01_small - Copy.las
Mins: [ 69.4041 -72.623 ]
Maxes: [187.6313  27.4519]
[128.5177  -22.58555]


In [23]:
print(pc_og)

[[  73.6044  -72.6143 1491.4239]
 [  73.6857  -72.6058 1491.4259]
 [  73.4483  -72.6154 1491.4249]
 ...
 [ 182.1178   20.0932 1504.2309]
 [ 182.2432   20.1013 1504.2469]
 [ 180.1315   12.0332 1537.3269]]


In [29]:
print(num)

81416921


In [36]:
file_path_3trees ="D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Riverton_park_03_3trees.las"


pc_3t,cords_3t,num_3t= load_file(file_path_3trees,return_num_points=True)


print(pc_3t)
print(cords_3t)
print(num_3t)

Loading file... D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Riverton_park_03_3trees.las
Mins: [ 713458.518 4766985.888]
Maxes: [ 713482.325 4767002.549]
[ 713470.4215 4766994.2185]
[[7.13460727e+05 4.76698631e+06 1.49178200e+03]
 [7.13460705e+05 4.76698600e+06 1.49180000e+03]
 [7.13460751e+05 4.76698637e+06 1.49176200e+03]
 ...
 [7.13478207e+05 4.76699996e+06 1.50162700e+03]
 [7.13478479e+05 4.76699999e+06 1.50200000e+03]
 [7.13478170e+05 4.76700000e+06 1.50161700e+03]]
['x', 'y', 'z']
4636739


In [38]:
file_path_3trees_P ="D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Riverton_park_03_3trees_FSCT_output\segmented.las"


pc_3t_P,cords_3t_P,num_3t_P= load_file(file_path_3trees_P,return_num_points=True)


print(pc_3t_P)
print(cords_3t_P)
print(num_3t_P)

Loading file... D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Riverton_park_03_3trees_FSCT_output\segmented.las
Mins: [ 713458.518 4766985.888]
Maxes: [ 713482.325 4767002.549]
[ 713470.4215 4766994.2185]
[[7.13460727e+05 4.76698631e+06 1.49178200e+03]
 [7.13460705e+05 4.76698600e+06 1.49180000e+03]
 [7.13460751e+05 4.76698637e+06 1.49176200e+03]
 ...
 [7.13478207e+05 4.76699996e+06 1.50162700e+03]
 [7.13478479e+05 4.76699999e+06 1.50200000e+03]
 [7.13478170e+05 4.76700000e+06 1.50161700e+03]]
['x', 'y', 'z']
4636739


In [39]:
file_path_3trees_odd ="D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Riverton_park_04_oddshape_FSCT_output\segmented.las"


pc_odd,cords_odd,num_odd= load_file(file_path_3trees_odd,return_num_points=True)


print(pc_odd)
print(cords_odd)
print(num_odd)

Loading file... D:\photogammetry\Projects\Flaming Tree Solutions\Exports\Riverton_park_04_oddshape_FSCT_output\segmented.las
Mins: [ 713428.697 4766775.887]
Maxes: [ 713643.275 4767014.093]
[ 713535.986 4766894.99 ]
[[7.13627131e+05 4.76701331e+06 1.49163300e+03]
 [7.13438808e+05 4.76677664e+06 1.49131000e+03]
 [7.13438717e+05 4.76677666e+06 1.49130900e+03]
 ...
 [7.13616984e+05 4.76700295e+06 1.50691600e+03]
 [7.13616894e+05 4.76700297e+06 1.50707900e+03]
 [7.13616933e+05 4.76700278e+06 1.50696400e+03]]
['x', 'y', 'z']
215367746
